// Generated by CoffeeScript 1.6.3
define(function(require, exports) {
  var colors, fontSize, lineHeight, lineWidth, paper, paper2, parser, render, startX, startY, text;
  parser = require('color');
  paper2 = document.querySelector('#paper');
  paper = paper2.getContext('2d');
  text = document.querySelector('#text');
  paper2.setAttribute('width', screen.width);
  paper2.setAttribute('height', screen.height);
  text.style.width = screen.width + 'px';
  text.style.height = screen.height + 'px';
  paper.font = '18px Monaco';
  lineWidth = 20;
  lineHeight = 20;
  fontSize = 20;
  startX = 10;
  startY = 40;
  colors = {
    func: 'yellow',
    para: 'gray',
    punc: 'hsl(262, 100%, 86%)',
    dollar: 'hsl(300, 100%, 73%)',
    string: 'hsl(60, 41%, 90%)',
    'string-text': 'hsl(60, 41%, 70%)',
    escape: 'hsl(0, 87%, 69%)',
    'escape-text': 'red'
  };
  render = function() {
    var before, countX, cursor, myx, myy, posx, posy;
    paper.clearRect(0, 0, screen.width, screen.height);
    countX = -1;
    parser(text.value).map(function(line) {
      var countY, x;
      countX += 1;
      x = startX + countX * lineWidth;
      countY = -1;
      return line.map(function(obj) {
        paper.fillStyle = colors[obj.type] || 'blue';
        return obj.text.split('').map(function(char) {
          var y;
          countY += 1;
          y = startY + countY * lineHeight;
          return paper.fillText(char, x, y);
        });
      });
    });
    cursor = text.selectionStart;
    before = text.value.slice(0, cursor).split('\n');
    posx = before.length - 1;
    posy = before[before.length - 1].length;
    myx = startX + posx * lineWidth;
    myy = startY + (posy - 1) * lineHeight;
    paper.fillStyle = 'white';
    return paper.fillRect(myx, myy + 10, 30, 2);
  };
  text.addEventListener('keyup', render);
  return render();
});
